# Mechanical zero offsets (radians)
# -------------------------------------------------
# Positive values rotate CCW when viewed
# from the motor’s back (Dynamixel convention).
# Start with zeros; update after dial-in.

offsets:
  # -------------  LEFT ARM  -------------
  l1:  134        # left_shoulder_flexionextension
  l2:  43      # left_shoulder_abductionadduction
  l3:  180       # left_elbow_rotation
  l4:  177      # left_elbow_flexionextension


  # -------------  RIGHT ARM -------------
  r1:  266        # right_shoulder_flexionextension
  r2:  45       # right_shoulder_abductionadduction
  r3:  173       # right_elbow_rotation
  r4:  93      # right_elbow_flexionextension


# 111        left_shoulder_flexionextension 
# 112        left_shoulder_abductionadduction  

# 121        left_elbow_flexionextension   
# 122        left_elbow_rotation  

# 211        right_shoulder_flexionextension  
# 212        right_shoulder_abductionadduction   

# 221        right_elbow_flexionextension 
# 222        right_elbow_rotation 