Header header
#From IMU
float64 accel_linear_xB
float64 accel_linear_yB
float64 accel_linear_zB
float64 accel_amplitude
#From IMU and wheel encoder
float64 velo_linear_xB_m_wheelLeft_gyroZ
float64 velo_linear_xB_m_wheelRight_gyroZ

#Frome wheel encoder only
float64 velo_linear_xB_m_wheel
float64 velo_angular_zB_m_wheel
float64 wheel_left_velo_rad
float64 wheel_right_velo_rad

#Best result
float64 vel_xM
float64 vel_yM
float64 vel_zM

float64 pos_xM
float64 pos_yM
float64 pos_zM

float64 roll
float64 pitch
float64 yaw

