#modify service based on the total number of joints in the robot
uint8 id1
uint8 id2
uint8 id3
uint8 id4
uint8 id5
uint8 id6
string item1
string item2
string item3
string item4
string item5
string item6
---
int32 value1
int32 value2
int32 value3
int32 value4
int32 value5
int32 value6
