pos:
  type: position_controllers/JointTrajectoryController
  joints:
    - l1
    - l2
    - l3
    - l4
  gains:
    l1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    l2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    l3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    l4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1