#Instead of using TAB for indentation, use two spaces at the place of one TAB
#Controller to control robot arm joints


robot_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [r1, r2, r3, r4, l1, l2, l3, l4]
#Controller to control end effector joints
hand_ee_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [lt, rt]
#Controller to continuously publish joint states/positions
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50
