// Generated by gencpp from file flo_humanoid_defs/GetJointVelocity.msg
// DO NOT EDIT!


#ifndef FLO_HUMANOID_DEFS_MESSAGE_GETJOINTVELOCITY_H
#define FLO_HUMANOID_DEFS_MESSAGE_GETJOINTVELOCITY_H

#include <ros/service_traits.h>


#include <flo_humanoid_defs/GetJointVelocityRequest.h>
#include <flo_humanoid_defs/GetJointVelocityResponse.h>


namespace flo_humanoid_defs
{

struct GetJointVelocity
{

typedef GetJointVelocityRequest Request;
typedef GetJointVelocityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetJointVelocity
} // namespace flo_humanoid_defs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::flo_humanoid_defs::GetJointVelocity > {
  static const char* value()
  {
    return "810f3b5a74591cab058ea94decd15832";
  }

  static const char* value(const ::flo_humanoid_defs::GetJointVelocity&) { return value(); }
};

template<>
struct DataType< ::flo_humanoid_defs::GetJointVelocity > {
  static const char* value()
  {
    return "flo_humanoid_defs/GetJointVelocity";
  }

  static const char* value(const ::flo_humanoid_defs::GetJointVelocity&) { return value(); }
};


// service_traits::MD5Sum< ::flo_humanoid_defs::GetJointVelocityRequest> should match
// service_traits::MD5Sum< ::flo_humanoid_defs::GetJointVelocity >
template<>
struct MD5Sum< ::flo_humanoid_defs::GetJointVelocityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::flo_humanoid_defs::GetJointVelocity >::value();
  }
  static const char* value(const ::flo_humanoid_defs::GetJointVelocityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::flo_humanoid_defs::GetJointVelocityRequest> should match
// service_traits::DataType< ::flo_humanoid_defs::GetJointVelocity >
template<>
struct DataType< ::flo_humanoid_defs::GetJointVelocityRequest>
{
  static const char* value()
  {
    return DataType< ::flo_humanoid_defs::GetJointVelocity >::value();
  }
  static const char* value(const ::flo_humanoid_defs::GetJointVelocityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::flo_humanoid_defs::GetJointVelocityResponse> should match
// service_traits::MD5Sum< ::flo_humanoid_defs::GetJointVelocity >
template<>
struct MD5Sum< ::flo_humanoid_defs::GetJointVelocityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::flo_humanoid_defs::GetJointVelocity >::value();
  }
  static const char* value(const ::flo_humanoid_defs::GetJointVelocityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::flo_humanoid_defs::GetJointVelocityResponse> should match
// service_traits::DataType< ::flo_humanoid_defs::GetJointVelocity >
template<>
struct DataType< ::flo_humanoid_defs::GetJointVelocityResponse>
{
  static const char* value()
  {
    return DataType< ::flo_humanoid_defs::GetJointVelocity >::value();
  }
  static const char* value(const ::flo_humanoid_defs::GetJointVelocityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FLO_HUMANOID_DEFS_MESSAGE_GETJOINTVELOCITY_H
