// Generated by gencpp from file flo_humanoid_defs/GetJointPosition.msg
// DO NOT EDIT!


#ifndef FLO_HUMANOID_DEFS_MESSAGE_GETJOINTPOSITION_H
#define FLO_HUMANOID_DEFS_MESSAGE_GETJOINTPOSITION_H

#include <ros/service_traits.h>


#include <flo_humanoid_defs/GetJointPositionRequest.h>
#include <flo_humanoid_defs/GetJointPositionResponse.h>


namespace flo_humanoid_defs
{

struct GetJointPosition
{

typedef GetJointPositionRequest Request;
typedef GetJointPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetJointPosition
} // namespace flo_humanoid_defs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::flo_humanoid_defs::GetJointPosition > {
  static const char* value()
  {
    return "114a36cda781057b95290a137ea72b98";
  }

  static const char* value(const ::flo_humanoid_defs::GetJointPosition&) { return value(); }
};

template<>
struct DataType< ::flo_humanoid_defs::GetJointPosition > {
  static const char* value()
  {
    return "flo_humanoid_defs/GetJointPosition";
  }

  static const char* value(const ::flo_humanoid_defs::GetJointPosition&) { return value(); }
};


// service_traits::MD5Sum< ::flo_humanoid_defs::GetJointPositionRequest> should match
// service_traits::MD5Sum< ::flo_humanoid_defs::GetJointPosition >
template<>
struct MD5Sum< ::flo_humanoid_defs::GetJointPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::flo_humanoid_defs::GetJointPosition >::value();
  }
  static const char* value(const ::flo_humanoid_defs::GetJointPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::flo_humanoid_defs::GetJointPositionRequest> should match
// service_traits::DataType< ::flo_humanoid_defs::GetJointPosition >
template<>
struct DataType< ::flo_humanoid_defs::GetJointPositionRequest>
{
  static const char* value()
  {
    return DataType< ::flo_humanoid_defs::GetJointPosition >::value();
  }
  static const char* value(const ::flo_humanoid_defs::GetJointPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::flo_humanoid_defs::GetJointPositionResponse> should match
// service_traits::MD5Sum< ::flo_humanoid_defs::GetJointPosition >
template<>
struct MD5Sum< ::flo_humanoid_defs::GetJointPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::flo_humanoid_defs::GetJointPosition >::value();
  }
  static const char* value(const ::flo_humanoid_defs::GetJointPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::flo_humanoid_defs::GetJointPositionResponse> should match
// service_traits::DataType< ::flo_humanoid_defs::GetJointPosition >
template<>
struct DataType< ::flo_humanoid_defs::GetJointPositionResponse>
{
  static const char* value()
  {
    return DataType< ::flo_humanoid_defs::GetJointPosition >::value();
  }
  static const char* value(const ::flo_humanoid_defs::GetJointPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FLO_HUMANOID_DEFS_MESSAGE_GETJOINTPOSITION_H
