// Generated by gencpp from file flo_humanoid_defs/GetJointPositions.msg
// DO NOT EDIT!


#ifndef FLO_HUMANOID_DEFS_MESSAGE_GETJOINTPOSITIONS_H
#define FLO_HUMANOID_DEFS_MESSAGE_GETJOINTPOSITIONS_H

#include <ros/service_traits.h>


#include <flo_humanoid_defs/GetJointPositionsRequest.h>
#include <flo_humanoid_defs/GetJointPositionsResponse.h>


namespace flo_humanoid_defs
{

struct GetJointPositions
{

typedef GetJointPositionsRequest Request;
typedef GetJointPositionsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetJointPositions
} // namespace flo_humanoid_defs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::flo_humanoid_defs::GetJointPositions > {
  static const char* value()
  {
    return "7b1fb47a48cf84af19e240b1f04307c5";
  }

  static const char* value(const ::flo_humanoid_defs::GetJointPositions&) { return value(); }
};

template<>
struct DataType< ::flo_humanoid_defs::GetJointPositions > {
  static const char* value()
  {
    return "flo_humanoid_defs/GetJointPositions";
  }

  static const char* value(const ::flo_humanoid_defs::GetJointPositions&) { return value(); }
};


// service_traits::MD5Sum< ::flo_humanoid_defs::GetJointPositionsRequest> should match
// service_traits::MD5Sum< ::flo_humanoid_defs::GetJointPositions >
template<>
struct MD5Sum< ::flo_humanoid_defs::GetJointPositionsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::flo_humanoid_defs::GetJointPositions >::value();
  }
  static const char* value(const ::flo_humanoid_defs::GetJointPositionsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::flo_humanoid_defs::GetJointPositionsRequest> should match
// service_traits::DataType< ::flo_humanoid_defs::GetJointPositions >
template<>
struct DataType< ::flo_humanoid_defs::GetJointPositionsRequest>
{
  static const char* value()
  {
    return DataType< ::flo_humanoid_defs::GetJointPositions >::value();
  }
  static const char* value(const ::flo_humanoid_defs::GetJointPositionsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::flo_humanoid_defs::GetJointPositionsResponse> should match
// service_traits::MD5Sum< ::flo_humanoid_defs::GetJointPositions >
template<>
struct MD5Sum< ::flo_humanoid_defs::GetJointPositionsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::flo_humanoid_defs::GetJointPositions >::value();
  }
  static const char* value(const ::flo_humanoid_defs::GetJointPositionsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::flo_humanoid_defs::GetJointPositionsResponse> should match
// service_traits::DataType< ::flo_humanoid_defs::GetJointPositions >
template<>
struct DataType< ::flo_humanoid_defs::GetJointPositionsResponse>
{
  static const char* value()
  {
    return DataType< ::flo_humanoid_defs::GetJointPositions >::value();
  }
  static const char* value(const ::flo_humanoid_defs::GetJointPositionsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FLO_HUMANOID_DEFS_MESSAGE_GETJOINTPOSITIONS_H
