// Generated by gencpp from file flo_humanoid_defs/GetJointVelocityResponse.msg
// DO NOT EDIT!


#ifndef FLO_HUMANOID_DEFS_MESSAGE_GETJOINTVELOCITYRESPONSE_H
#define FLO_HUMANOID_DEFS_MESSAGE_GETJOINTVELOCITYRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace flo_humanoid_defs
{
template <class ContainerAllocator>
struct GetJointVelocityResponse_
{
  typedef GetJointVelocityResponse_<ContainerAllocator> Type;

  GetJointVelocityResponse_()
    : velocity(0)  {
    }
  GetJointVelocityResponse_(const ContainerAllocator& _alloc)
    : velocity(0)  {
  (void)_alloc;
    }



   typedef int32_t _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::flo_humanoid_defs::GetJointVelocityResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flo_humanoid_defs::GetJointVelocityResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetJointVelocityResponse_

typedef ::flo_humanoid_defs::GetJointVelocityResponse_<std::allocator<void> > GetJointVelocityResponse;

typedef boost::shared_ptr< ::flo_humanoid_defs::GetJointVelocityResponse > GetJointVelocityResponsePtr;
typedef boost::shared_ptr< ::flo_humanoid_defs::GetJointVelocityResponse const> GetJointVelocityResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::flo_humanoid_defs::GetJointVelocityResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::flo_humanoid_defs::GetJointVelocityResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::flo_humanoid_defs::GetJointVelocityResponse_<ContainerAllocator1> & lhs, const ::flo_humanoid_defs::GetJointVelocityResponse_<ContainerAllocator2> & rhs)
{
  return lhs.velocity == rhs.velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::flo_humanoid_defs::GetJointVelocityResponse_<ContainerAllocator1> & lhs, const ::flo_humanoid_defs::GetJointVelocityResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace flo_humanoid_defs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::flo_humanoid_defs::GetJointVelocityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flo_humanoid_defs::GetJointVelocityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flo_humanoid_defs::GetJointVelocityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flo_humanoid_defs::GetJointVelocityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flo_humanoid_defs::GetJointVelocityResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flo_humanoid_defs::GetJointVelocityResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::flo_humanoid_defs::GetJointVelocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1221446a6cb55fc620353cce70eed4a";
  }

  static const char* value(const ::flo_humanoid_defs::GetJointVelocityResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1221446a6cb55fcULL;
  static const uint64_t static_value2 = 0x620353cce70eed4aULL;
};

template<class ContainerAllocator>
struct DataType< ::flo_humanoid_defs::GetJointVelocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "flo_humanoid_defs/GetJointVelocityResponse";
  }

  static const char* value(const ::flo_humanoid_defs::GetJointVelocityResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::flo_humanoid_defs::GetJointVelocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 velocity\n"
"\n"
;
  }

  static const char* value(const ::flo_humanoid_defs::GetJointVelocityResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::flo_humanoid_defs::GetJointVelocityResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetJointVelocityResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::flo_humanoid_defs::GetJointVelocityResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::flo_humanoid_defs::GetJointVelocityResponse_<ContainerAllocator>& v)
  {
    s << indent << "velocity: ";
    Printer<int32_t>::stream(s, indent + "  ", v.velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLO_HUMANOID_DEFS_MESSAGE_GETJOINTVELOCITYRESPONSE_H
