(cl:defpackage flo_humanoid_defs-srv
  (:use )
  (:export
   "GETJOINTPOSITION"
   "<GETJOINTPOSITION-REQUEST>"
   "GETJOINTPOSITION-REQUEST"
   "<GETJOINTPOSITION-RESPONSE>"
   "GETJOINTPOSITION-RESPONSE"
   "GETJOINTPOSITIONS"
   "<GETJOINTPOSITIONS-REQUEST>"
   "GETJOINTPOSITIONS-REQUEST"
   "<GETJOINTPOSITIONS-RESPONSE>"
   "GETJOINTPOSITIONS-RESPONSE"
   "GETJOINTVELOCITY"
   "<GETJOINTVELOCITY-REQUEST>"
   "GETJOINTVELOCITY-REQUEST"
   "<GETJOINTVELOCITY-RESPONSE>"
   "GETJOINTVELOCITY-RESPONSE"
  ))

