controller_list:
  - name: fake_armr_controller
    type: $(arg fake_execution_type)
    joints:
      - r1
      - r2
      - r3
      - r4
  - name: fake_handr_controller
    type: $(arg fake_execution_type)
    joints:
      - rt
initial:  # Define initial robot poses per group
#  - group: armr
#    pose: home

  []