#This is a movit contoller connecting follow_joint_trajectory controller with JointTrajectoryController
controller_list:
  - name: robot_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
    - r1
    - r2
    - r3
    - r4
    - l1
    - l2
    - l3
    - l4
  - name: hand_ee_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
    - lt
    - rt
