(cl:defpackage dynamixel_sdk_examples-srv
  (:use )
  (:export
   "BULKGETITEM"
   "<BULKGETITEM-REQUEST>"
   "BULKGETITEM-REQUEST"
   "<BULKGETITEM-RESPONSE>"
   "BULKGETITEM-RESPONSE"
   "GETPOSITION"
   "<GETPOSITION-REQUEST>"
   "GETPOSITION-REQUEST"
   "<GETPOSITION-RESPONSE>"
   "GETPOSITION-RESPONSE"
   "SYNCGETPOSITION"
   "<SYNCGETPOSITION-REQUEST>"
   "SYNCGETPOSITION-REQUEST"
   "<SYNCGETPOSITION-RESPONSE>"
   "SYNCGETPOSITION-RESPONSE"
  ))

