// Generated by gencpp from file dynamixel_sdk_examples/BulkSetItem.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_SDK_EXAMPLES_MESSAGE_BULKSETITEM_H
#define DYNAMIXEL_SDK_EXAMPLES_MESSAGE_BULKSETITEM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dynamixel_sdk_examples
{
template <class ContainerAllocator>
struct BulkSetItem_
{
  typedef BulkSetItem_<ContainerAllocator> Type;

  BulkSetItem_()
    : id1(0)
    , id2(0)
    , item1()
    , item2()
    , value1(0)
    , value2(0)  {
    }
  BulkSetItem_(const ContainerAllocator& _alloc)
    : id1(0)
    , id2(0)
    , item1(_alloc)
    , item2(_alloc)
    , value1(0)
    , value2(0)  {
  (void)_alloc;
    }



   typedef uint8_t _id1_type;
  _id1_type id1;

   typedef uint8_t _id2_type;
  _id2_type id2;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _item1_type;
  _item1_type item1;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _item2_type;
  _item2_type item2;

   typedef int32_t _value1_type;
  _value1_type value1;

   typedef int32_t _value2_type;
  _value2_type value2;





  typedef boost::shared_ptr< ::dynamixel_sdk_examples::BulkSetItem_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamixel_sdk_examples::BulkSetItem_<ContainerAllocator> const> ConstPtr;

}; // struct BulkSetItem_

typedef ::dynamixel_sdk_examples::BulkSetItem_<std::allocator<void> > BulkSetItem;

typedef boost::shared_ptr< ::dynamixel_sdk_examples::BulkSetItem > BulkSetItemPtr;
typedef boost::shared_ptr< ::dynamixel_sdk_examples::BulkSetItem const> BulkSetItemConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamixel_sdk_examples::BulkSetItem_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamixel_sdk_examples::BulkSetItem_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dynamixel_sdk_examples::BulkSetItem_<ContainerAllocator1> & lhs, const ::dynamixel_sdk_examples::BulkSetItem_<ContainerAllocator2> & rhs)
{
  return lhs.id1 == rhs.id1 &&
    lhs.id2 == rhs.id2 &&
    lhs.item1 == rhs.item1 &&
    lhs.item2 == rhs.item2 &&
    lhs.value1 == rhs.value1 &&
    lhs.value2 == rhs.value2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dynamixel_sdk_examples::BulkSetItem_<ContainerAllocator1> & lhs, const ::dynamixel_sdk_examples::BulkSetItem_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dynamixel_sdk_examples

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dynamixel_sdk_examples::BulkSetItem_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamixel_sdk_examples::BulkSetItem_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_sdk_examples::BulkSetItem_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_sdk_examples::BulkSetItem_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_sdk_examples::BulkSetItem_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_sdk_examples::BulkSetItem_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamixel_sdk_examples::BulkSetItem_<ContainerAllocator> >
{
  static const char* value()
  {
    return "57637498ac8b526dd9c5ab3d57aff27d";
  }

  static const char* value(const ::dynamixel_sdk_examples::BulkSetItem_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x57637498ac8b526dULL;
  static const uint64_t static_value2 = 0xd9c5ab3d57aff27dULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamixel_sdk_examples::BulkSetItem_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamixel_sdk_examples/BulkSetItem";
  }

  static const char* value(const ::dynamixel_sdk_examples::BulkSetItem_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamixel_sdk_examples::BulkSetItem_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id1\n"
"uint8 id2\n"
"string item1\n"
"string item2\n"
"int32 value1\n"
"int32 value2\n"
;
  }

  static const char* value(const ::dynamixel_sdk_examples::BulkSetItem_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamixel_sdk_examples::BulkSetItem_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id1);
      stream.next(m.id2);
      stream.next(m.item1);
      stream.next(m.item2);
      stream.next(m.value1);
      stream.next(m.value2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BulkSetItem_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamixel_sdk_examples::BulkSetItem_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamixel_sdk_examples::BulkSetItem_<ContainerAllocator>& v)
  {
    s << indent << "id1: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id1);
    s << indent << "id2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id2);
    s << indent << "item1: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.item1);
    s << indent << "item2: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.item2);
    s << indent << "value1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.value1);
    s << indent << "value2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.value2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMIXEL_SDK_EXAMPLES_MESSAGE_BULKSETITEM_H
